### ISSUE TITLE
StrPack might be add to REQUIRE

### ISSUE THREAD

**Issue by s-celles** [JuliaBerry/PiGPIO.jl#2]
StrPack is used at
https://github.com/JuliaBerry/PiGPIO.jl/blob/master/src/PiGPIO.jl#L276
maybe it should be add to REQUIRE

**Comment by aviks** [comment]
Yes, thanks. I just tagged StrPack to work on 0.5, will fix this as well.

**Comment by aviks** [comment]
Hi Sebastien, 

From this, and a message on discource, it looks like you may be looking to improve this library. I also am working on that, so might be useful to compare notes. 

My general plan is to clean this library up, and implement a task/channel based interface for asynchronous input. Once that is done, I want to build a higher level api similar to GPIOZero.

**Comment by s-celles** [comment]
Hi Avik,

yes a higher level interface comparable to Python projects such as [GPIOZero](https://gpiozero.readthedocs.io/en/stable/) or [Pingo](http://www.pingo.io/docs/) could be a great idea.

What is important in such a lib is to not rely only on RaspberryPi devices.

It should also work (contrary to GPIOZero) on other board (such as BeagleBone) or attached devices such as Arduino with Arduino Firmata.

So Pingo may be a better target for this than GPIOZero.
But GPIOZero have a nice API (see https://github.com/pingo-io/pingo-py/issues/110 )


I suggest to also have a look at
- https://github.com/RaspberryPi-Samples/roadmap/issues/1
- https://gist.github.com/scls19fr/0e95131dc3ec6cd061da11377445215d#file-pingo-jl-L103

A signal/slot library or a publish/subscribe library is probably required but I also think that API should work both with asynchronous in mind but also "parts" should also be able to work in non threading context in mind (see https://github.com/pingo-io/pingo-py/issues/107 )

Kind regards
