### ISSUE TITLE
connection to Pi refused

### ISSUE THREAD

**Issue by jwassmer** [JuliaBerry/PiGPIO.jl#4]
using Pi() gives me

julia> Pi()
ERROR: connect: connection refused (ECONNREFUSED)

julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 4 (v7l)
  WORD_SIZE: 32
  BLAS: libopenblas (NO_LAPACKE NO_AFFINITY ARMV6)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.8

**Comment by aviks** [comment]
Do you have the `pigpiod` daemon started?
