### ISSUE TITLE
Precompiling Error under Julia 1.0

### ISSUE THREAD

**Issue by ChristianF88** [JuliaBerry/PiGPIO.jl#6]
Hi,

I'm running Julia on my Raspberry Pi.
Unfortunately I cant use the PiGPIO package due to the problems below.
(I did alread try Pkg.add("StrPack")... it added the package but the precompilation error is still occuring)

```
using PiGPIO
[ Info: Precompiling PiGPIO [bb151fc1-c6dc-5496-8ed6-07f94907e623]
ERROR: LoadError: syntax: extra token "DataAlign" after end of expression
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:319 [inlined]
 [6] eval(::Expr) at ./client.jl:389
 [7] top-level scope at ./none:3
in expression starting at /home/pi/.julia/packages/StrPack/v7Klf/src/StrPack.jl:18
ERROR: LoadError: Failed to precompile StrPack [e44e80c3-c1a0-5445-b28e-0e14522c62bc] to /home/pi/.julia/compiled/v1.0/StrPack/UhIcV.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] require(::Module, ::Symbol) at ./logging.jl:311
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/pi/.julia/dev/PiGPIO/src/PiGPIO.jl:270
ERROR: Failed to precompile PiGPIO [bb151fc1-c6dc-5496-8ed6-07f94907e623] to /home/pi/.julia/compiled/v1.0/PiGPIO/8aGxa.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] require(::Module, ::Symbol) at ./logging.jl:311
```

Any Suggestions?

Thanks a lot!

Christian

**Comment by aviks** [comment]
Yeah, this package needs significant modifications to make it compatible with 1.0. I haven't had the time to get it done, hopefully soon.

**Comment by ChristianF88** [comment]
Well then first of all, thank you for your answer! I hope you get around to it some time soon ;)

Have a great one!!

**Comment by Ellipse0934** [comment]
Should we first upgrade `StrPack.jl` or is it redundant with the new infrastructure ?

**Comment by vc1492a** [comment]
@aviks thanks for the comment! I'm interested in using Julia 1.0+ for GPIO, looking forward to using it :relaxed: Is there any new information on making the modifications needed for the update? I'm using Python in my current project, but am looking for rewriting some of that functionality in Julia as I believe it will bring a performance improvement. Thanks!

**Comment by aviks** [comment]
Sorry not much progress. Could do with some help.

**Comment by vc1492a** [comment]
Thanks @aviks. Do you think this is something a beginner in Julia could jump into? I haven't touched Julia since version 0.3 was out, but want to help if I can.

**Comment by Ellipse0934** [comment]
@vc1492a I made a PR(#7 ) which is able to run on 1.0 . However, everything might not be working, I will be looking into refactoring the code and making things better. You can clone my fork until the PR is in an acceptable state. 

> I believe it (julia) will bring a performance improvement

That might not be the case, this package is probably on par with the python package. The data *processing* yes, but the data acquisition and control part is mostly a no. Essentially both the python and the Julia package communicate with the pigpio daemon via a network socket which runs in the background. 
See https://github.com/joan2937/pigpio/issues/129 for a better understanding.

**Comment by vc1492a** [comment]
@Ellipse0934 thank you for submitting the PR and for your comments regarding the performance improvement - I'll be doing some data processing along with the GPIO library so using Julia will help there, even if the GPIO functionality is comparable with Python (I found the link you provided helpful!). I'll try to check this out soon and report back if I run into any issues that should be looked at in the PR.

**Comment by Ellipse0934** [comment]
You could also consider the option of not running julia on the pi. Since the daemon allows external comms you could run it on your main computer and connect both(pi and main comp) to the same network. Find your pi's ip addr then:
`pi = Pi(host = "192.168.0.1", port = "8888")` from your main computer's julia.

**Comment by Ellipse0934** [comment]
The package now compiles on 1.0 and basic features like `set_mode`, `get_mode` are working. The package is still a WIP.
